server-name:
  skyblock: 'skyblock'
  survival: 'survival'

server-group:
  party:
    name: 'Parties Games'
    servers:
      - party1
      - party2
      - party3
  infect:
    name: 'Infection Games'
    servers:
      - infect1
      - infect2
      - infect3

messages:
  total-players: "&eTotal online players&f: &a%total_players%"
  server-group-format: "&r%group_name%&r&f: &f%player_count% &f[%player_names%]"
  server-format: "&r%server_name%&r&f: &f%player_count% &7[%player_names%]"
  reload: '&aVelocityList is reloaded.'
  no-group-or-server: '&cCannnot find this server.'
  no-permission: '&cNo permission'
